#! /bin/sh

# Load Intel compiler. See
# https://usgs.slack.com/archives/GAHHHLN0L/p1527276939000444
module load intel/psxe-2018u1 netcdf-parallel/4.4.1-intel
./configure
#  NETCDF_INC=$NETCDF_F_INC NETCDF_LIB=$NETCDF_F_LIB
